### ISSUE TITLE
Dear Author, How could I install you library?

### ISSUE THREAD

**Issue by williamXDB** [gpospelov/qt-mvvm#320]
Dear Author,
  My QtCreator version is V4.3.1

**Comment by gpospelov** [comment]
Hi,

it's a CMake C++ project, it is distributed as a source code. It can be compiled in Qt-creator as any other CMake-based project. Details vary slightly depending on the compiler used, and the operation system. There are quite a number of tutorials about CMake and Qt. See some discussion [here](https://forum.qt.io/topic/103502/how-to-load-and-open-cmake-project-in-qtcreator).

**Comment by williamXDB** [comment]
Thank you ,I have tried ,the error below:
 Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
CMake version 3.19.3
CMake Error at cmake/modules/configuration.cmake:46 (find_package):
  Could not find a configuration file for package "Qt5" that is compatible
  with requested version "5.12".

  The following configuration files were considered but not accepted:

    E:/Qt/Qt5.9.0/5.9/mingw53_32/lib/cmake/Qt5/Qt5Config.cmake, version: 5.9.0
    E:/Qt/Qt5.9.0/5.9/winrt_x86_msvc2017/lib/cmake/Qt5/Qt5Config.cmake, version: 5.9.0

Call Stack (most recent call first):
  CMakeLists.txt:12 (include)

**Comment by gpospelov** [comment]
So, from the log, it is clear that you are on Windows. The log says that `Qt 5.12` is required, but you have `Qt 5.9.0` installed. Your local Qt installation is too old.  Also, the log mentions `mingw 32bit` compiler and I do not have experience with `mingw`. My recommendation would be to go to the latest long-term-support Qt 5.15.2 + msvc2019 compiler (which you get for free when you install the latest Microsoft Visual Studio Community Edition). And then compile the whole thing from Qt-creator. At some point, I will provide a step-by-step tutorial. But this will take time.
