### ISSUE TITLE
compile error by Qt5.12.0

### ISSUE THREAD

**Issue by isteelcx** [gpospelov/qt-mvvm#337]
![图片](https://user-images.githubusercontent.com/45957575/204081241-628dc92b-9cf4-4c6c-a688-38ecd993407f.png)

**Comment by gpospelov** [comment]
Hello,

looks like your compiler is not fully c++17 compliant. It uses `experimental` version of `filesystem` library, that doesn't contain `is_regular_file` method. 

You can try to compile qt-mvvm without `filesystem` support using `cmake -DMVVM_ENABLE_FILESYSTEM=OFF <source>` or upgrade your compiler to a more recent version.

Regards

**Comment by isteelcx** [comment]
ok thank you！
Can you recommend any other NodeEditor projects besides yours?

**Comment by gpospelov** [comment]
I saw one C++/QML [here](https://github.com/cneben/QuickQanava)

Regards

**Comment by isteelcx** [comment]
> I saw one C++/QML [here](https://github.com/cneben/QuickQanava)
> 
> 
> 
> Regards

what about this one？https://github.com/paceholder/nodeeditor

**Comment by gpospelov** [comment]
Seems to be very mature and worth trying

Regards
