### ISSUE TITLE
Why was this project removed from Bornagain？

### ISSUE THREAD

**Issue by incity** [gpospelov/qt-mvvm#340]
I saw the bornagain here : https://jugit.fz-juelich.de/mlz/bornagain
the v1.19.0 version use MVVM, But it was removed later, and I don't know what caused it.
I want to use MVVM in my project, but I'm not sure if there are any issues with this project.
@gpospelov could you help?

**Comment by gpospelov** [comment]
Hello, 
thank you for your interest in the project, qt-mvvm is not developed anymore and might be archived soon. I do not have time to support it, unfortunately. I will modify README accordingly. As for the BornAgain, I'm not working for them for the moment and can't say where they are heading. Regards.
