### ISSUE TITLE
Remove GoogleTest git submodule

### ISSUE THREAD

**Issue by yurtpage** [gpospelov/qt-mvvm#342]
The GoogleTest library is added as a git submodule.
Today you can install it from a repository i.e. in Debian/Ubuntu `apt instal libgtest-dev`.
There is also `googletest` package with all its sources.
I believe that same is true for other Linus distros.
So maybe you can unlink the GTest from sources?

https://cmake.org/cmake/help/latest/module/GoogleTest.html

**Comment by gpospelov** [comment]
Yes, will do. Thanks for the suggestion

**Comment by gpospelov** [comment]
Resolved in #345
