### ISSUE TITLE
Consider alternative names instead of "viewmodel"

### ISSUE THREAD

**Issue by jwuttke** [gpospelov/qt-mvvm#50]
How to maximize the cognitive load of keeping a concept X apart from the related concepts "model" and "view"? Right, choose a name like X="view model".

There may be good theoretical grounds for the term "view model", but for API users and library codevelopers it is about the worst possible choice.

Wikipedia says "The view model has been described as a state of the data in the model." What then about the term "state"? Other suggestions?

**Comment by gpospelov** [comment]
Cognitive load is also person-dependent. I named it ViewModel because it is a ViewModel  from Model/View/ViewModel design pattern and I though it is not a bad idea to keep naming consistent. Will think about it more.
