### ISSUE TITLE
Directory structure: Shorten source tree

### ISSUE THREAD

**Issue by jwuttke** [gpospelov/qt-mvvm#52]
For command-line addicts, `source/libmvvm_viewmodel/mvvm/` is painful. Also, I see no good reason for such verbosity.

What about
```
lib/model
lib/state
```
(`state` to replace `viewmodel` as per #50)

Or create _two_ libraries, and have an even flatter directory structure
```
libmodel
libstate
```

**Comment by gpospelov** [comment]
I was following to http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1204r0.html.

**Comment by jwuttke** [comment]
According to that document, the leading `source/` should be omitted

**Comment by gpospelov** [comment]
> According to that document, the leading `source/` should be omitted
I'm not sure if I remember this statement, seems that I have to read the document again.

There is something in that line
> The project's source code is placed into a subdirectory of the root directory named the same as the project, for example, hello/hello/ or libhello/libhello/. It is called the project's source subdirectory.

I could rename my "source" to "qt-mvvm" but frankly speaking I prefer my current structure.
Another option would be to move libraries one level up, but when amount of my libraries will grow, top level directory will look messy.
