### ISSUE TITLE
discuss case for MVVM_TESTS_AUTOEXEC

### ISSUE THREAD

**Issue by jwuttke** [gpospelov/qt-mvvm#55]
why not rely on standard ways to run tests?

**Comment by gpospelov** [comment]
I have implemented MVVM_TESTS_AUTOEXEC to conveniently disable test executton from IDE when I want to debug test execution itself in the debugger.

I have implemented MVVM_TESTS_AUTODISCOVERY to experiment with google test discovery and fully rely on ctest. Still experimenting...

**Comment by gpospelov** [comment]
Reopen to make this part of cmake machinery less confusing

**Comment by gpospelov** [comment]
Resolved in #57
