### ISSUE TITLE
Visual Studio 2019 compiler crash on trying to compile tests

### ISSUE THREAD

**Issue by DmitryYurov** [gpospelov/qt-mvvm#9]
With the following message:

C:\Users\DmitryYurov\Documents\Software\qt-mvvm\Source\tests\viewmodel\TestAxisPlotControllers.cpp : fatal error C1001: An internal error has occurred in the compiler.
    (compiler file 'd:\agent\_work\3\s\src\vctools\Compiler\Utc\src\p2\main.c', line 160)
     To work around this problem, try simplifying or changing the program near the locations listed above.
    Please choose the Technical Support command on the Visual C++
     Help menu, or open the Technical Support help file for more information
    Internal Compiler Error in C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\CL.exe.  You will be prompted to send an error report to Microsoft later.
    INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\CL.exe'
        Please choose the Technical Support command on the Visual C++
        Help menu, or open the Technical Support help file for more information

**Comment by gpospelov** [comment]
Resolved in #100
